export const songs = [
  "This is ground control to Major Tom You`ve really made the grade",
  "Man is an obstacle, sad as the clown, Oh by jingo So hold on to nothing, and he wont let you down, Oh jingo",
  "It`s been a hard days night, and I`ve been working like a dog",
  "Imagine there is no Heaven",
  "Purple Haze all around, don`t know if I`m coming up or down",
  "Is you is or is you ain`t my baby",
  "Is you is or is you aint my baby",
  "I`m just a gigolo, everywhere I go People know the part I`m playing",
  "I am the passenger And I ride and I ride",
  "Now so long, Marianne, it`s time that we began to laugh and cry and cry and laugh about it all again. ",
  "The minor fall, the major lift The baffled king composing Hallelujah",
  "Like a complete unknown Like a rolling stone ?",
  "Lets get hot on the dancing spot, oh let`s get cool in the pool,",
  "I`ve been working from seven to eleven every night, I said It kinda makes my life a drag Lord, that aint right",
  "Were`nt for whiskey and wimmin, I`d have money today",
  "Oh my Lola, lolololo Lola, lolololo Lola",
  "Always look on the bright side of life",
  "In the House of the Rising Sun",
];
